### ISSUE TITLE
Simple way to brick EC during update. Plug in the USB

### ISSUE THREAD

**Issue by jempabroni** [betrusted-io/betrusted-ec#17]
The update process for the EC (via Xous) turns the screen blank without warning. Connecting a charger during this process appears to interrupt the update and cause the device to reboot, leaving the EC with effectively corrupted gateware. 

My precursor now won't respond to keypresses when it boots up, and the screen shows a "smoltcp ff:ff:ff:ff:ff:ff is not a multicast address," so I have to factory restore it with the Pi HAT. Luckily I won't lose any data.

**Comment by bunnie** [comment]
Ouch.

Do you recall which version of Xous you were upgrading from when this happened, and what method you were using to do the update (there's a couple of scripts that can be run to do it). 

The charger circuit is in fact connected to the EC, but during an update the interrupt pin that would try to trigger an EC event should be ignored because the EC is being updated. 

But ... you know what, I bet I know where the interrupt might be trigger-able and I bet the EC handles it but because the host is trying to do the update it refuses to acknowledge the interrupt and so the EC stops writing the update. I'll have a look into that path.

Thanks for reporting this, and sorry for the troubles :(

**Comment by bunnie** [comment]
I was unable to reproduce the issue on my setup by plugging in USB during an update, but, I did find a possible code path where if the SoC power state monitoring pins glitch during an update the EC could decide the SoC has powered down and it should ignore further commands from the SoC. I've added that to be within the "update lock", so that the EC will ignore any reports of SoC power state changes in the middle of an update routine.

Hopefully that addresses the issue, if you see it again please re-open and I will try to find more ways to reproduce the issue.
